spring:
  data:
    redis:
     host: localhost
     port: 6379
  kafka:
    bootstrap-servers: localhost:9092
chatroom:
  service:
    url: http://localhost:8085
server:
  port: 8084
  config:
    import: "configserver:"