spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: chatMessagesDb
  kafka:
    bootstrap-servers: localhost:9092
server:
  port: 8086
  config:
    import: "configserver:"